### ISSUE TITLE
Site can't be reached

### ISSUE THREAD

**Issue by Sattishh** [GreenTreeTeam/ChillingMusic#7]
I ran into this repository and when I opened the link: ``https://chillingmusic.cf/``

It takes a long time to load and eventually says "This site can't be reached"

Error Code: DNS_PROBE_FINISHED_NXDOMAIN

It may just been an issue with my computer but this is the first time I'm running into something like this. Could be something wrong with the DNS Server or Hosting Server?

Hope y'all can figure it out. 
Goodluck :)

**Comment by yashraj-n** [comment]
Hello, It looks like you're having a bad time with your internet.
What we recommend you to do is open the command prompt and type
```bash
tracert 1.1.1.1
```
and check if what's wrong, for me it's like this
![tracertValue](https://cosi.is-inside.me/LAtKcTRZ.png)

This problem is most likely because of ISP you're using

If the issue persists, reply to this thread with a screenshot of `tracert 1.1.1.1`

**Comment by yashraj-n** [comment]
If the issue persists,

Open command prompt and type
```bash
ipconfig/flushdns
```
then restart your system

After that, open the command prompt again and type

```bash
ipconfig/release
```
which will release your current IP address (you cant access internet, you need to restart your system in order to use internet again)

and again type
```bash
ipconfig/flushdns # will flush dns cache
ipconfig/renew # will renew configuration settings for all adapters
netsh int ip set dns # reinstate winsock
netsh winsock reset # reset winsock
```
Once that is done, restart your computer

**Comment by Sattishh** [comment]
> Hello, It looks like you're having a bad time with your internet.
> What we recommend you to do is open the command prompt and type
> 
> ```shell
> tracert 1.1.1.1
> ```
> 
> and check if what's wrong, for me it's like this
> ![tracertValue](https://camo.githubusercontent.com/8fa207ec208f647323866860f6c90655ab7cc9f7b267564e2cbd6cf3479735cc/68747470733a2f2f636f73692e69732d696e736964652e6d652f4c41744b6354525a2e706e67)
> 
> This problem is most likely because of ISP you're using
> 
> If the issue persists, reply to this thread with a screenshot of `tracert 1.1.1.1`

Thank you for the quick response! What problem should I be looking for in the Command Prompt?

**Comment by yashraj-n** [comment]
No, check if you can establish a tracert connection to 1.1.1.1, if yes what is the ping

**Comment by Sattishh** [comment]
![image](https://user-images.githubusercontent.com/51452387/116820281-6ace0080-ab9e-11eb-9c14-1b6752c9e80a.png)
This is the result

**Comment by yashraj-n** [comment]
try ```bash
tracert chillingmusic.cf
```

**Comment by Sattishh** [comment]
```Unable to resolve target system name chillingmusic.cf.```

**Comment by Sattishh** [comment]
Seems to be an issue with my internet completely. On my cellular data, it works perfectly. Atleast it's good to know that the website is all good. 

I'm gonna close this issue since it's my WiFi issue.
